### ISSUE TITLE
Upload 0.0.1.0 to Hackage?

### ISSUE THREAD

**Issue by googleson78** [chshersh/type-errors-pretty#6]
Hi!

Is there something holding back the `0.0.1.0` version of this package from being uploaded to Hackage?

I am interested because I want to get `polysemy` to build with the latest stackage nightlies for ghc 8.8

Thanks in advance!

**Comment by chshersh** [comment]
@googleson78 Sorry, I somehow missed your issue! And I don't understand why I missed it :thinking: 
Nothing stops from uploading version `0.0.1.0` to Hackage. I just wanted to do #3 first, that's why I didn't upload after adding support for GHC-8.8.1. But Hacktoberfest hasn't ended yet (and issue #3 is for Hacktoberfest), so I will just upload a new version of `type-errors-pretty` to Hackage.

**Comment by chshersh** [comment]
It's on Hackage:

* https://hackage.haskell.org/package/type-errors-pretty-0.0.1.0
